### PR TITLE
Add a legend

### LINKED ISSUE #17: Add a legend
The rendered pages need a legend included to explain the various visual elements of the diagrams.

Below is a list of legend items for diagrams. Please discuss it in this issue.

> If an item below is checked, it has been verified.

- [x] circles - Actors
- [x] arrows connecting components - One-directional data/information flow
- [x] lines connecting components (without arrowheads) - Bidirectional data/information flow
- [x] dotted lines - Data/information request that is system generated, rather than actor requested (e.g. authentication, or container creation)
- [ ] ~~labels on lines/arrows - Description of the data/information being transferred~~
- [x] square transparent boxes - Groups of components that together serve as a larger component
- [x] blue boxes - Component (which may be comprised of sub-components)
- [x] flags - External data components
- [x] diamonds - Collections of VMs or Containers

/cc @LinuxBozo

### PR DESCRIPTION
**Pull request by rogeruiz**
~~This patch series is a work in progress.~~ Closes #17

### CODE REVIEW

**Comment by rogeruiz** [comment]
screen shot 2016-10-05 at 5 18 40 pm

**Comment by rogeruiz** [comment]
This should be good to be reviewed!

/cc @afeld @brittag @LinuxBozo

**Comment by LinuxBozo** [comment]
@rogeruiz unless things have changed, circles are the actors (and if we're using SSP terms, I think the term might be "User Type" maybe?  rounded edges will be something that's an abstract thing that isn't a VM/Container, like Email, Text Message, or Build in Concourse, etc..

**Comment by rogeruiz** [comment]
Ah okay. Thanks @linuxbozo. I think I made a mistake in copying things from the issue. I'll update it and include the round-edges with what you said

**Comment by brittag** [comment]
@rogeruiz Is there a way to also include an example of a blue box (for a group of components)?

**Comment by rogeruiz** [comment]
Sure thing @brittag. Would it just say `Collection of components` or something along those lines?

**Comment by brittag** [comment]
@rogeruiz Hm, I'd defer to @LinuxBozo on how to define this. Maybe just `Group of components`? It looks like sometimes it's a formal logical group defined by software (such as an AWS environment) and sometimes it's an informal grouping, so a broad term seems helpful.

**Comment by rogeruiz** [comment]
Updated legend. The last two commits update the legend to reflect @LinuxBozo's and @brittag's suggestions.

screen shot 2016-10-05 at 10 02 35 pm

**Comment by NoahKunin** [comment]
Looks good to us for now!

**Pull request merged**
